---
- name: "Create user {{ user }}"
  user: 
    name: "{{ user }}"
    shell: "{{ user_shell }}"
  
- name: "Add {{ user }} user to sudoers"
  copy:
    dest: "/etc/sudoers.d/{{ user }}"
    content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"

- name: "Add authorization key"
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '{{ public_key_path }}') }}" 
    state: present
  notify:
    - restart ssh